### ISSUE TITLE
차트 페이지 생성

### ISSUE THREAD

**Issue by seongbin9786** [seongbin9786/pre-onboarding-9th-3-4#2]
## Tasks
- [x] 공통 레이아웃 생성
- [x] 페이지 컴포넌트 생성 및 차트 렌더링
- [x] 화면 로딩 상태 구현
